// Code generated by protoc-gen-go. DO NOT EDIT.
// source: linkseller-service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Linkseller struct {
	Person               *Person  `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	Machine              *Machine `protobuf:"bytes,2,opt,name=machine,proto3" json:"machine,omitempty"`
	Order                *Order   `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Linkseller) Reset()         { *m = Linkseller{} }
func (m *Linkseller) String() string { return proto.CompactTextString(m) }
func (*Linkseller) ProtoMessage()    {}
func (*Linkseller) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f023b9d5cecd0fc, []int{0}
}

func (m *Linkseller) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Linkseller.Unmarshal(m, b)
}
func (m *Linkseller) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Linkseller.Marshal(b, m, deterministic)
}
func (m *Linkseller) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Linkseller.Merge(m, src)
}
func (m *Linkseller) XXX_Size() int {
	return xxx_messageInfo_Linkseller.Size(m)
}
func (m *Linkseller) XXX_DiscardUnknown() {
	xxx_messageInfo_Linkseller.DiscardUnknown(m)
}

var xxx_messageInfo_Linkseller proto.InternalMessageInfo

func (m *Linkseller) GetPerson() *Person {
	if m != nil {
		return m.Person
	}
	return nil
}

func (m *Linkseller) GetMachine() *Machine {
	if m != nil {
		return m.Machine
	}
	return nil
}

func (m *Linkseller) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type Person struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Document             string   `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f023b9d5cecd0fc, []int{1}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Person) GetDocument() string {
	if m != nil {
		return m.Document
	}
	return ""
}

type Machine struct {
	Modelcode            int64    `protobuf:"varint,1,opt,name=modelcode,proto3" json:"modelcode,omitempty"`
	Seriesnumber         string   `protobuf:"bytes,2,opt,name=seriesnumber,proto3" json:"seriesnumber,omitempty"`
	Value                float64  `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Model                string   `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Chip                 string   `protobuf:"bytes,5,opt,name=chip,proto3" json:"chip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Machine) Reset()         { *m = Machine{} }
func (m *Machine) String() string { return proto.CompactTextString(m) }
func (*Machine) ProtoMessage()    {}
func (*Machine) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f023b9d5cecd0fc, []int{2}
}

func (m *Machine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Machine.Unmarshal(m, b)
}
func (m *Machine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Machine.Marshal(b, m, deterministic)
}
func (m *Machine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Machine.Merge(m, src)
}
func (m *Machine) XXX_Size() int {
	return xxx_messageInfo_Machine.Size(m)
}
func (m *Machine) XXX_DiscardUnknown() {
	xxx_messageInfo_Machine.DiscardUnknown(m)
}

var xxx_messageInfo_Machine proto.InternalMessageInfo

func (m *Machine) GetModelcode() int64 {
	if m != nil {
		return m.Modelcode
	}
	return 0
}

func (m *Machine) GetSeriesnumber() string {
	if m != nil {
		return m.Seriesnumber
	}
	return ""
}

func (m *Machine) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Machine) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Machine) GetChip() string {
	if m != nil {
		return m.Chip
	}
	return ""
}

type Order struct {
	Ordercode            int64    `protobuf:"varint,1,opt,name=ordercode,proto3" json:"ordercode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f023b9d5cecd0fc, []int{3}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetOrdercode() int64 {
	if m != nil {
		return m.Ordercode
	}
	return 0
}

type CreateRequest struct {
	Api                  string      `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Linkseller           *Linkseller `protobuf:"bytes,2,opt,name=linkseller,proto3" json:"linkseller,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f023b9d5cecd0fc, []int{4}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateRequest) GetLinkseller() *Linkseller {
	if m != nil {
		return m.Linkseller
	}
	return nil
}

type CreateResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f023b9d5cecd0fc, []int{5}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Linkseller)(nil), "v1.Linkseller")
	proto.RegisterType((*Person)(nil), "v1.Person")
	proto.RegisterType((*Machine)(nil), "v1.Machine")
	proto.RegisterType((*Order)(nil), "v1.Order")
	proto.RegisterType((*CreateRequest)(nil), "v1.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "v1.CreateResponse")
}

func init() { proto.RegisterFile("linkseller-service.proto", fileDescriptor_6f023b9d5cecd0fc) }

var fileDescriptor_6f023b9d5cecd0fc = []byte{
	// 552 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xbf, 0x6f, 0x13, 0x31,
	0x1c, 0xc5, 0x75, 0x49, 0x93, 0x92, 0x6f, 0x21, 0x6a, 0x0d, 0x43, 0x88, 0x8a, 0x38, 0x59, 0xaa,
	0x84, 0x2a, 0x7a, 0xd7, 0x84, 0x0e, 0xa8, 0x2c, 0xfc, 0xd8, 0x10, 0x08, 0x30, 0x03, 0x23, 0x72,
	0x7c, 0x5f, 0x72, 0x6e, 0xef, 0x6c, 0x63, 0xfb, 0xd2, 0xb2, 0xb2, 0xb2, 0xc1, 0xc6, 0xbf, 0xc5,
	0xc2, 0xc0, 0xc8, 0x1f, 0x82, 0xce, 0x77, 0xed, 0x35, 0x2a, 0x53, 0xec, 0x8f, 0x5f, 0xde, 0x7b,
	0xfe, 0x71, 0x30, 0x29, 0xa4, 0x3a, 0x75, 0x58, 0x14, 0x68, 0x0f, 0x1c, 0xda, 0x95, 0x14, 0x98,
	0x18, 0xab, 0xbd, 0x26, 0xbd, 0xd5, 0x6c, 0xba, 0xbb, 0xd4, 0x7a, 0x59, 0x60, 0xca, 0x8d, 0x4c,
	0xb9, 0x52, 0xda, 0x73, 0x2f, 0xb5, 0x72, 0x8d, 0x62, 0xfa, 0x30, 0xfc, 0x88, 0x83, 0x25, 0xaa,
	0x03, 0x77, 0xc6, 0x97, 0x4b, 0xb4, 0xa9, 0x36, 0x41, 0x71, 0x5d, 0x4d, 0xcf, 0x01, 0x5e, 0x5d,
	0x66, 0x11, 0x0a, 0x43, 0x83, 0xd6, 0x69, 0x35, 0x89, 0xe2, 0xe8, 0xc1, 0xd6, 0x1c, 0x92, 0xd5,
	0x2c, 0x79, 0x1b, 0x08, 0x6b, 0x57, 0xc8, 0x1e, 0x6c, 0x96, 0x5c, 0xe4, 0x52, 0xe1, 0xa4, 0x17,
	0x44, 0x5b, 0xb5, 0xe8, 0x75, 0x83, 0xd8, 0xc5, 0x1a, 0xb9, 0x0f, 0x03, 0x6d, 0x33, 0xb4, 0x93,
	0x7e, 0x10, 0x8d, 0x6a, 0xd1, 0x9b, 0x1a, 0xb0, 0x86, 0xd3, 0xc7, 0x30, 0x6c, 0x9c, 0x09, 0x81,
	0x0d, 0xff, 0xc5, 0x60, 0xc8, 0x1c, 0xb1, 0x30, 0x26, 0x53, 0xb8, 0x91, 0x69, 0x51, 0x95, 0xa8,
	0x7c, 0x88, 0x19, 0xb1, 0xcb, 0x39, 0xfd, 0x16, 0xc1, 0x66, 0x9b, 0x47, 0x76, 0x61, 0x54, 0xea,
	0x0c, 0x0b, 0xa1, 0xb3, 0xc6, 0xa0, 0xcf, 0x3a, 0x40, 0x28, 0xdc, 0x74, 0x68, 0x25, 0x3a, 0x55,
	0x95, 0x0b, 0xb4, 0xad, 0xd3, 0x1a, 0x23, 0x77, 0x60, 0xb0, 0xe2, 0x45, 0x85, 0xa1, 0x68, 0xc4,
	0x9a, 0x49, 0x4d, 0x83, 0xcd, 0x64, 0x23, 0xfc, 0xa5, 0x99, 0xd4, 0x4d, 0x45, 0x2e, 0xcd, 0x64,
	0xd0, 0x34, 0xad, 0xc7, 0x74, 0x0f, 0x06, 0x61, 0x5f, 0x75, 0x95, 0xb0, 0xb3, 0xab, 0x55, 0x2e,
	0x01, 0x7d, 0x07, 0xb7, 0x5e, 0x58, 0xe4, 0x1e, 0x19, 0x7e, 0xae, 0xd0, 0x79, 0xb2, 0x0d, 0x7d,
	0x6e, 0x64, 0xbb, 0xe9, 0x7a, 0x48, 0x12, 0x80, 0xee, 0xde, 0xdb, 0xc3, 0x1d, 0xd7, 0xe7, 0xd6,
	0xdd, 0x10, 0xbb, 0xa2, 0xa0, 0x73, 0x18, 0x5f, 0x58, 0x3a, 0xa3, 0x95, 0xc3, 0xff, 0x78, 0x8e,
	0xa1, 0x27, 0xb3, 0xe0, 0xd5, 0x67, 0x3d, 0x99, 0xcd, 0x3f, 0xc2, 0x4e, 0xe7, 0xf6, 0xbe, 0x79,
	0x5a, 0xe4, 0x25, 0x0c, 0x1b, 0x23, 0xb2, 0x53, 0xc7, 0xad, 0xf5, 0x9c, 0x92, 0xab, 0xa8, 0xc9,
	0xa1, 0x77, 0xbf, 0xfe, 0xfa, 0xfb, 0xa3, 0x77, 0x9b, 0x8e, 0xd3, 0xd5, 0x2c, 0xed, 0x1a, 0x1d,
	0x47, 0xfb, 0xcf, 0xff, 0x44, 0xdf, 0x9f, 0xfd, 0x8e, 0x88, 0x05, 0xd2, 0xf1, 0xb8, 0x7d, 0xc3,
	0xf4, 0xc3, 0x1a, 0x35, 0x56, 0x9f, 0xa0, 0xf0, 0x84, 0xe6, 0xde, 0x1b, 0x77, 0x9c, 0xa6, 0x4b,
	0xe9, 0xf3, 0x6a, 0x91, 0x08, 0x5d, 0xa6, 0xce, 0x63, 0xa1, 0xd3, 0x45, 0xc1, 0xc5, 0x69, 0xa9,
	0x2d, 0x4e, 0xef, 0x09, 0x6e, 0x0b, 0xed, 0x92, 0x4f, 0x68, 0x15, 0x57, 0x19, 0xba, 0xa7, 0x41,
	0x51, 0x6b, 0x93, 0x85, 0x9d, 0xf7, 0x67, 0xc9, 0xe1, 0x7e, 0x14, 0xcd, 0xb7, 0xb9, 0x31, 0x85,
	0x14, 0xe1, 0x89, 0xa7, 0x27, 0x4e, 0xab, 0xe3, 0x6b, 0x84, 0x3d, 0x81, 0xfe, 0xd1, 0xe1, 0x11,
	0x39, 0x82, 0x7d, 0x86, 0xbe, 0xb2, 0x0a, 0xb3, 0xf8, 0x2c, 0x47, 0x15, 0xfb, 0x1c, 0x63, 0x8b,
	0x4e, 0x57, 0x56, 0x60, 0x9c, 0x69, 0x74, 0xb1, 0xd2, 0x3e, 0xc6, 0x73, 0xe9, 0x7c, 0x42, 0x86,
	0xb0, 0xf1, 0xb3, 0x17, 0x6d, 0x2e, 0x86, 0xe1, 0xb3, 0x79, 0xf4, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0x08, 0xd0, 0x84, 0x6c, 0xa2, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LinksellerServiceClient is the client API for LinksellerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LinksellerServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type linksellerServiceClient struct {
	cc *grpc.ClientConn
}

func NewLinksellerServiceClient(cc *grpc.ClientConn) LinksellerServiceClient {
	return &linksellerServiceClient{cc}
}

func (c *linksellerServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/v1.LinksellerService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinksellerServiceServer is the server API for LinksellerService service.
type LinksellerServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
}

func RegisterLinksellerServiceServer(s *grpc.Server, srv LinksellerServiceServer) {
	s.RegisterService(&_LinksellerService_serviceDesc, srv)
}

func _LinksellerService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinksellerServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.LinksellerService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinksellerServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LinksellerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.LinksellerService",
	HandlerType: (*LinksellerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _LinksellerService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "linkseller-service.proto",
}
